can select distribution of container

diff --git a/templates/lxc-debian.erb b/templates/lxc-debian.erb
--- a/templates/lxc-debian.erb
+++ b/templates/lxc-debian.erb
@@ -80,15 +80,16 @@ EOF
 
 download_debian()
 {
-    packages="libui-dialog-perl,dialog,ifupdown,iputils-ping,locales,isc-dhcp-client,netbase,net-tools,iproute,openssh-server,bind9-host,vim,sudo,lsb-release"
+    packages="libui-dialog-perl,dialog,ifupdown,iputils-ping,locales,isc-dhcp-client,netbase,net-tools,iproute,openssh-server,bind9-host,vim,sudo,lsb-release,cron,rubygems"
 
     cache=$1
     arch=$2
+    dist=$3
 
     # check the mini debian was not already downloaded
     mkdir -p "$cache/partial-$arch"
     if [ $? -ne 0 ]; then
-	echo "Failed to create '$cache/partial-$arch' directory"
+	echo "Failed to create '$cache/partial-$dist-$arch' directory"
 	return 1
     fi
 
@@ -96,16 +97,16 @@ download_debian()
     echo "Downloading debian minimal ..."
     debootstrap --verbose --variant=minbase --arch=$arch \
 	--include $packages \
-	squeeze $cache/partial-$arch http://ftp.de.debian.org/debian
+	$dist $cache/partial-$dist-$arch http://ftp.de.debian.org/debian
     if [ $? -ne 0 ]; then
 	echo "Failed to download the rootfs, aborting."
 	return 1
     fi
 	# adding one console device
-	mknod -m 660 $cache/partial-$arch/dev/tty1 c 5 1
-	chown root:tty $cache/partial-$arch/dev/tty1
+	mknod -m 660 $cache/partial-$dist-$arch/dev/tty1 c 5 1
+	chown root:tty $cache/partial-$dist-$arch/dev/tty1
 	
-    mv "$1/partial-$arch" "$1/rootfs-$arch"
+    mv "$1/partial-$dist-$arch" "$1/rootfs-$dist-$arch"
     echo "Download complete."
 
     return 0
@@ -116,10 +117,11 @@ copy_debian()
     cache=$1
     arch=$2
     rootfs=$3
+    dist=$4
 
     # make a local copy of the minidebian
     echo -n "Copying rootfs to $rootfs..."
-    cp -a $cache/rootfs-$arch $rootfs || return 1
+    cp -a $cache/rootfs-$dist-$arch $rootfs || return 1
     return 0
 }
 
@@ -127,6 +129,8 @@ install_debian()
 {
     cache="/var/cache/lxc/debian"
     rootfs=$1
+    dist=$2
+    
     mkdir -p /var/lock/subsys/
     (
 	flock -n -x 200
@@ -144,16 +148,16 @@ install_debian()
 	    arch=i386
 	fi
 
-	echo "Checking cache download in $cache/rootfs-$arch ... "
-	if [ ! -e "$cache/rootfs-$arch" ]; then
-	    download_debian $cache $arch
+	echo "Checking cache download in $cache/rootfs-$dist-$arch ... "
+	if [ ! -e "$cache/rootfs-$dist-$arch" ]; then
+	    download_debian $cache $arch $dist
 	    if [ $? -ne 0 ]; then
 		echo "Failed to download 'debian base'"
 		return 1
 	    fi
 	fi
 
-	copy_debian $cache $arch $rootfs
+	copy_debian $cache $arch $rootfs $dist
 	if [ $? -ne 0 ]; then
 	    echo "Failed to copy rootfs"
 	    return 1
@@ -251,7 +255,7 @@ EOF
     return 0
 }
 
-options=$(getopt -o hp:n:c -l help,path:,name:,clean -- "$@")
+options=$(getopt -o hp:n:d:c -l help,path:,name:,clean,dist: -- "$@")
 if [ $? -ne 0 ]; then
         usage $(basename $0)
 	exit 1
@@ -263,8 +267,9 @@ do
     case "$1" in
         -h|--help)      usage $0 && exit 0;;
         -p|--path)      path=$2; shift 2;;
-	-n|--name)      name=$2; shift 2;;
-	-c|--clean)     clean=$2; shift 2;;
+		-n|--name)      name=$2; shift 2;;
+		-c|--clean)     clean=$2; shift 2;;
+		-d|--dist)      dist=$2; shift 2;;
         --)             shift 1; break ;;
         *)              break ;;
     esac
@@ -273,6 +278,10 @@ done
 if [ ! -z "$clean" -a -z "$path" ]; then
     clean || exit 1
     exit 0
+fi
+
+if [ -z "$dist" ]; then
+	dist="squeeze"
 fi
 
 type debootstrap
@@ -293,19 +302,19 @@ fi
 
 rootfs=$path/rootfs
 
-install_debian $rootfs
+install_debian $rootfs $dist
 if [ $? -ne 0 ]; then
     echo "failed to install debian"
     exit 1
 fi
 
-configure_debian $rootfs $name
+configure_debian $rootfs $name $dist
 if [ $? -ne 0 ]; then
     echo "failed to configure debian for a container"
     exit 1
 fi
 
-copy_configuration $path $rootfs
+copy_configuration $path $rootfs $dist
 if [ $? -ne 0 ]; then
     echo "failed write configuration file"
     exit 1
